window.COVE_RECORDS = [
 {category:'Budget',year:'2026-27',title:'Proposed Budget',summary:'City Budget Department lists the FY 2026-27 proposed budget alongside adopted budget records.',source:'https://www.copperascovetx.gov/185/Adopted-Budgets',status:'Primary source'},
 {category:'Capital',year:'2026-30',title:'Capital Improvement Plan',summary:'Adopted long-range capital plan. Track original project cost, amendments, schedule changes and actual expenditures.',source:'https://www.copperascovetx.gov/184/Long-Range-Plans',status:'Primary source'},
 {category:'Payroll',year:'Current',title:'Employee Benefits / TMRS',summary:'Regular city employees participate in TMRS. Build total-compensation records from salary, overtime, allowances, insurance and retirement costs.',source:'https://www.copperascovetx.gov/200/Benefits',status:'Primary source'},
 {category:'Water',year:'2026',title:'Systemwide pressure-loss event',summary:'Saved city snapshot records a water-main break at Golf Course Road and Texas Street, pressure loss, boil-water notice and recovery updates.',source:'https://www.copperascovetx.gov/CivicAlerts.aspx',status:'Captured snapshot'},
 {category:'Water',year:'2026',title:'Stage 4C implementation',summary:'Saved city homepage captured Stage 4C as an active emergency alert during the August 2026 water event.',source:'https://www.copperascovetx.gov/AlertCenter.aspx',status:'Captured snapshot'},
 {category:'Wastewater',year:'Current',title:'Wastewater treatment operations',summary:'Track treatment plants, permitted capacity, average flows, staffing, expansions, maintenance and capital spending.',source:'https://www.copperascovetx.gov/248/Waste-Water',status:'Primary source'},
 {category:'Solid Waste',year:'Current',title:'Solid Waste Department',summary:'Track fees, collection costs, equipment, fleet, staffing, recycling, transfer operations and capital projects.',source:'https://www.copperascovetx.gov/250/Solid-Waste',status:'Primary source'},
 {category:'Golf',year:'Research',title:'Golf course financial ledger',summary:'Build revenue-vs-expense history including payroll, equipment, irrigation, water source, capital projects and transfers/subsidies.',source:'https://www.copperascovetx.gov/',status:'Research queue'},
 {category:'Dominion',year:'Research',title:'Dominion / Fort Cavazos money trail',summary:'Trace grant award, city agreement, recipient, project expenditures, amendments and delivered infrastructure.',source:'https://www.copperascovetx.gov/',status:'Research queue'},
 {category:'Debt & Grants',year:'2026',title:'Certificates of Obligation',summary:'City resolutions include notices and actions involving certificates of obligation. Track proceeds, debt service and funded projects.',source:'https://www.copperascovetx.gov/189/City-Resolutions',status:'Primary source'},
 {category:'Budget',year:'2026',title:'Budget amendments',summary:'City ordinances include amendments to the FY 2025-26 budget. Each amendment should be linked back to the original appropriation.',source:'https://www.copperascovetx.gov/190/City-Ordinances',status:'Primary source'},
 {category:'Payroll',year:'2026',title:'Personnel Improvement Plan amendments',summary:'Personnel-plan amendments can reveal positions added, removed, reclassified or moved after the original long-range plan was adopted.',source:'https://www.copperascovetx.gov/190/City-Ordinances',status:'Primary source'}
];
window.COVE_TIMELINE = [
 {year:'Historic',title:'Archived financial reports',text:'Older city financial reports provide actual revenue and expense snapshots that can be normalized into year-over-year series.'},
 {year:'FY 2023-2027 → FY 2027-2031',title:'Long-range plans',text:'Compare each successive CIP, Capital Outlay Plan and Personnel Improvement Plan to find projects or positions that move, change cost or disappear.'},
 {year:'2026',title:'Budget and personnel amendments',text:'Ordinances amend adopted financial and personnel plans after adoption. These become change events, not replacement history.'},
 {year:'Aug. 16, 2026',title:'Water main break / pressure loss',text:'Saved city snapshot preserves the current public explanation and emergency notices as the endpoint for the infrastructure timeline.'}
];
